apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: yolab-cephfs
  resources:
    requests:
      storage: {{ .Values.config.storage_size | default "50Gi" | quote }}
---
{{ include "yolab-common.caddyConfigMap" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-admin
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  
  password: {{ required "config.password is required" .Values.config.password | quote }}
