{{ include "yolab-common.caddyConfigMap" . }}
---
{{ include "yolab-common.uninstallHook" . }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: yolab-cephfs
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      initContainers:
      {{- include "yolab-common.wgRegisterInit" . | nindent 6 }}
      {{- include "yolab-common.fileExplorerInit" . | nindent 6 }}
      containers:
      {{- include "yolab-common.gatewayContainers" . | nindent 6 }}
      - name: ollama
        image: ollama/ollama:latest@sha256:4dea9fb511947e24a84237bb636b0203abcb2ff0d3fbc7b4ff865deb91362131
        imagePullPolicy: IfNotPresent
        readinessProbe:
          tcpSocket:
            port: 11434
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 11434
          initialDelaySeconds: 30
          periodSeconds: 20
          failureThreshold: 3
        volumeMounts:
        - name: data
          mountPath: /root/.ollama
          subPath: {{ .Release.Name }}/ollama
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:main@sha256:6a773e5c3a246b65cbe74ce942b294292c0e5f81c138f703d111bc162f7d7c3d
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 20
          failureThreshold: 3
        env:
        - name: OLLAMA_BASE_URL
          value: http://localhost:11434
        volumeMounts:
        - name: data
          mountPath: /app/backend/data
          subPath: {{ .Release.Name }}/open-webui
      volumes:
      {{- include "yolab-common.gatewayVolumes" . | nindent 6 }}
