apiVersion: v2
name: mazanoke
description: A self-hosted local image optimizer
type: application
version: 0.1.1
appVersion: 1.1.7
dependencies:
- name: yolab-common
  version: "0.1.14"
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Mazanoke
  yolab.io/icon: 📁
  yolab.io/category: files
  yolab.io/tagline: A self-hosted local image optimizer
  yolab.io/github: civilblur/mazanoke
  yolab.io/collections: replace-google
home: https://mazanoke.com/
