apiVersion: v2
name: booklore
description: An app for managing and reading books
type: application
version: 0.1.0
appVersion: 2.4.0
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: BookLore
  yolab.io/icon: 📁
  yolab.io/category: files
  yolab.io/tagline: An app for managing and reading books
  yolab.io/github: booklore-app/booklore
  yolab.io/collections: replace-google
home: https://demo.booklore.dev/login
