apiVersion: v2
name: syncthing
description: "Continuous file synchronization between your devices"
home: https://syncthing.net
type: application
version: 0.1.12

dependencies:
  - name: yolab-common
    version: "0.1.11"
    repository: "oci://ghcr.io/demycode/charts"

annotations:
  yolab.io/display-name: "Syncthing"
  yolab.io/icon: "🔄"
  yolab.io/category: "utilities"
