apiVersion: v2
name: searxng
description: "Privacy-respecting metasearch engine"
home: https://docs.searxng.org
type: application
version: 0.1.17
appVersion: "1"

dependencies:
  - name: yolab-common
    version: "0.1.15"
    repository: "oci://ghcr.io/demycode/charts"

annotations:
  yolab.io/display-name: "SearXNG"
  yolab.io/icon: "🔎"
  yolab.io/category: "utilities"
  yolab.io/github: "searxng/searxng"
  yolab.io/tagline: "Private web search without tracking"
  yolab.io/collections: "replace-google,privacy"
