apiVersion: v2
name: dawarich
description: "Self-hosted location history and travel tracking"
home: https://dawarich.app
type: application
version: 0.1.8

dependencies:
  - name: yolab-common
    version: "0.1.6"
    repository: "oci://ghcr.io/demycode/charts"

annotations:
  yolab.io/display-name: "Dawarich"
  yolab.io/icon: "🗺️"
  yolab.io/category: "productivity"
