config:
  subdomain: dawarich
  time_zone: UTC
yolab:
  fileExplorer:
    protect:
    - postgres
    - redis
  platformApiUrl: ''
  accountToken: ''
  serviceName: ''
  gateway:
    upstream: localhost:3000
