{{ include "yolab-common.caddyConfigMap" . }}
---
{{ include "yolab-common.fileExplorerSecret" . }}
---
{{ include "yolab-common.fileExplorerConfigMap" . }}
---
{{ include "yolab-common.privateAccessResources" . }}
---
{{ include "yolab-common.uninstallHook" . }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: yolab-cephfs
  resources:
    requests:
      storage: {{ .Values.config.storage_size | default "10Gi" | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  admin_password: {{ required "config.admin_password is required" .Values.config.admin_password | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      initContainers:
      {{- include "yolab-common.wgRegisterInit" . | nindent 6 }}
      {{- include "yolab-common.fileExplorerInit" . | nindent 6 }}
      {{- include "yolab-common.privateAccessInit" . | nindent 6 }}
      containers:
      {{- include "yolab-common.gatewayContainers" . | nindent 6 }}
      {{- include "yolab-common.fileExplorerContainer" . | nindent 6 }}
      {{- include "yolab-common.privateAccessContainers" . | nindent 6 }}
      - name: archivebox
        image: archivebox/archivebox:0.9.73@sha256:d4720d86c0e91577bccaee59fa238d22a9cfc0674aa594c80f739f0738270af9
        imagePullPolicy: IfNotPresent
        env:
        - name: APP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: '{{ .Release.Name }}-secrets'
              key: admin_password
        - name: ALLOWED_HOSTS
          value: '*'
        - name: ADMIN_USERNAME
          value: admin
        - name: ADMIN_PASSWORD
          value: $(APP_PASSWORD)
        - name: PUBLIC_INDEX
          value: 'True'
        - name: PUBLIC_SNAPSHOTS
          value: 'True'
        - name: PUBLIC_ADD_VIEW
          value: 'False'
        ports:
        - containerPort: 5797
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - wget -q -O /dev/null http://127.0.0.1:5797/public/ || exit 1
          initialDelaySeconds: 180
          periodSeconds: 30
        volumeMounts:
        - name: data
          mountPath: /data
          subPath: '{{ .Release.Name }}/data'
        - name: data
          mountPath: /tmp/archivebox
          subPath: '{{ .Release.Name }}/tmp'
      volumes:
      {{- include "yolab-common.gatewayVolumes" . | nindent 6 }}
      {{- include "yolab-common.fileExplorerVolumes" . | nindent 6 }}
      {{- include "yolab-common.privateAccessVolumes" . | nindent 6 }}
