apiVersion: v2
name: planka
description: "Kanban boards for projects and teams"
home: https://planka.app
type: application
version: 0.1.9
appVersion: "1"

dependencies:
  - name: yolab-common
    version: "0.1.8"
    repository: "oci://ghcr.io/demycode/charts"

annotations:
  yolab.io/display-name: "Planka"
  yolab.io/icon: "📋"
  yolab.io/category: "productivity"
