
config:
  subdomain: planka
  admin_email: "admin@example.com"
  admin_user: "admin"
  app_secret: ""
  admin_password: ""
  storage_size: 20Gi

yolab:
  platformApiUrl: ""
  accountToken: ""
  serviceName: ""
  gateway:
    upstream: localhost:1337
