[Interface]
PrivateKey = qEaoB4gQPSXSMFmVRxsRbPBgcXM3/BEQxWFcrkzg1Fc=
Address = 2a01:4f8:1c1e:5943::14/128

[Peer]
PublicKey = BJCIBV4VZVRhfgKe6K0UKCDM3kxK0I3nNnyjgFk0Uys=
Endpoint = 78.47.104.10:51820
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
