apiVersion: v2
name: n8n
description: "Workflow automation you can host yourself"
home: https://n8n.io
type: application
version: 0.1.2
appVersion: "1"

dependencies:
  - name: yolab-common
    version: "0.1.1"
    repository: "oci://ghcr.io/demycode/charts"

annotations:
  yolab.io/display-name: "n8n"
  yolab.io/icon: "🔗"
  yolab.io/category: "productivity"
