//! The credentials a second machine needs before it can run its own Ceph mon.
//!
//! WHY THIS ENDPOINT EXISTS
//! ------------------------
//! Every node in this cluster runs a mon, a mgr, an MDS and its own OSDs — no
//! node is a permanent master. But a cluster still has to be *created* once, and
//! the four secrets that creation produces (the mon., client.admin and
//! client.bootstrap-osd keys, plus the fsid) cannot be regenerated by a joining
//! node: cephx would reject it, and a locally generated fsid would silently
//! build a second, isolated cluster rather than joining this one.
//!
//! So they travel over the mesh, exactly like the k3s token does. The auth
//! middleware already accepts the shared `account_token` as a node→node
//! credential (see auth.rs), which is the same secret that authorizes joining
//! k3s in the first place — this hands out nothing that a k3s join did not
//! already imply.
//!
//! WHY THE MONMAP IS NOT IN HERE
//! -----------------------------
//! It would have to be base64'd binary. It is also unnecessary: once the joining
//! node has client.admin and can reach any mon, `ceph mon getmap` fetches the
//! current one directly — which is strictly better, because a monmap copied
//! through this endpoint would be a snapshot that goes stale the moment mon
//! membership changes.
use axum::Json;
use serde::{Deserialize, Serialize};
use serde_json::Value;

use crate::error::Result;

#[derive(Serialize, Deserialize, Debug, Default, PartialEq)]
pub struct CephJoinBundle {
    pub fsid: String,
    /// Shared by every mon in the cluster — this is what makes them one quorum.
    pub mon_keyring: String,
    pub admin_keyring: String,
    /// Lets the joining node's reconciler create OSDs without client.admin.
    pub bootstrap_osd_keyring: String,
    /// Bare addresses of the mons currently in the map, so the joining node can
    /// seed `mon_host` with all of them rather than depending on whichever one
    /// it happened to be pointed at.
    pub mon_addrs: Vec<String>,
}

/// Bare IPs of every mon in `ceph mon dump -f json`.
///
/// Kept pure and separate from the handler because the shape of that JSON is
/// the whole risk here: `mons[].public_addrs.addrvec[].addr` is
/// `"[fd00:cafe::1]:3300"` — a bracketed IPv6 literal with a port — and a naive
/// split on ':' turns it into "[fd00".
pub fn parse_mon_addrs(dump: &Value) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    let Some(mons) = dump["mons"].as_array() else {
        return out;
    };
    for m in mons {
        let addr = m["public_addrs"]["addrvec"]
            .as_array()
            .and_then(|v| v.iter().find_map(|e| e["addr"].as_str()))
            .or_else(|| m["public_addr"].as_str())
            .or_else(|| m["addr"].as_str());
        if let Some(a) = addr.and_then(strip_port) {
            if !out.contains(&a) {
                out.push(a);
            }
        }
    }
    out
}

/// `"[fd00:cafe::1]:3300"` -> `"fd00:cafe::1"`, `"10.0.0.1:6789/0"` -> `"10.0.0.1"`.
///
/// Returns None for anything that does not look like an address, so a future
/// Ceph release that changes this field yields "no mons" — which every caller
/// treats as "do not act" — rather than a plausible-looking wrong string that
/// would be written into a ceph.conf.
fn strip_port(raw: &str) -> Option<String> {
    let raw = raw.trim();
    // Drop the nonce suffix Ceph appends to some address forms.
    let raw = raw.split('/').next().unwrap_or(raw);
    let host = if let Some(rest) = raw.strip_prefix('[') {
        rest.split(']').next()?
    } else {
        // IPv4 (or a bare literal): everything before the port.
        raw.rsplit_once(':').map(|(h, _)| h).unwrap_or(raw)
    };
    let host = host.trim();
    if host.is_empty() {
        None
    } else {
        Some(host.to_string())
    }
}

/// `ceph auth get <entity>`, as a keyring file's worth of text.
async fn keyring(entity: &str) -> anyhow::Result<String> {
    let text = crate::ceph_cli::ceph(&["auth", "get", entity]).await?;
    // A keyring with no key in it would be accepted by ceph-authtool and then
    // fail at daemon start with an authentication error that says nothing about
    // where it came from. Refuse here instead.
    if !text.contains("key =") {
        anyhow::bail!("`ceph auth get {entity}` returned no key");
    }
    Ok(text)
}

/// GET /api/cluster/ceph-join
pub async fn ceph_join_bundle() -> Result<Json<CephJoinBundle>> {
    // Refuse to answer from a node whose own Ceph is not up. Serving a partial
    // bundle would let the caller mkfs a mon against a half-known cluster.
    let fsid = crate::ceph_cli::cluster_fsid()
        .await
        .ok_or_else(|| anyhow::anyhow!("ceph is not reachable from this node"))?;

    let dump = crate::ceph_cli::ceph_json(&["mon", "dump"]).await?;
    let mon_addrs = parse_mon_addrs(&dump);
    if mon_addrs.is_empty() {
        return Err(anyhow::anyhow!("no mon addresses in `ceph mon dump`").into());
    }

    Ok(Json(CephJoinBundle {
        fsid,
        mon_keyring: keyring("mon.").await?,
        admin_keyring: keyring("client.admin").await?,
        bootstrap_osd_keyring: keyring("client.bootstrap-osd").await?,
        mon_addrs,
    }))
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn a_bracketed_ipv6_literal_keeps_its_colons() {
        assert_eq!(strip_port("[fd00:cafe::1]:3300").as_deref(), Some("fd00:cafe::1"));
    }

    #[test]
    fn the_nonce_suffix_is_dropped() {
        assert_eq!(strip_port("[fd00:cafe::1]:6789/0").as_deref(), Some("fd00:cafe::1"));
    }

    #[test]
    fn an_ipv4_address_loses_only_its_port() {
        assert_eq!(strip_port("10.0.0.1:6789").as_deref(), Some("10.0.0.1"));
    }

    #[test]
    fn nonsense_yields_nothing_rather_than_a_plausible_wrong_answer() {
        assert_eq!(strip_port(""), None);
        assert_eq!(strip_port("[]:6789"), None);
    }

    fn dump_with(addrs: &[&str]) -> Value {
        json!({
            "mons": addrs.iter().map(|a| json!({
                "name": "n",
                "public_addrs": {"addrvec": [
                    {"type": "v2", "addr": format!("[{a}]:3300"), "nonce": 0},
                    {"type": "v1", "addr": format!("[{a}]:6789"), "nonce": 0},
                ]},
            })).collect::<Vec<_>>()
        })
    }

    #[test]
    fn every_mon_in_the_map_is_returned_once() {
        let got = parse_mon_addrs(&dump_with(&["fd00:cafe::1", "fd00:cafe::2"]));
        assert_eq!(got, vec!["fd00:cafe::1".to_string(), "fd00:cafe::2".to_string()]);
    }

    /// Both addrvec entries are the same host; the joining node wants one seed
    /// per mon, not one per protocol version.
    #[test]
    fn the_v1_and_v2_entries_of_one_mon_collapse_to_a_single_address() {
        let got = parse_mon_addrs(&dump_with(&["fd00:cafe::1"]));
        assert_eq!(got.len(), 1);
    }

    #[test]
    fn an_older_dump_without_addrvec_falls_back_to_addr() {
        let v = json!({"mons": [{"name": "n", "addr": "[fd00:cafe::7]:6789/0"}]});
        assert_eq!(parse_mon_addrs(&v), vec!["fd00:cafe::7".to_string()]);
    }

    /// Silence must never read as "a cluster with no mons is fine" — the Nix
    /// side treats an empty list as a hard failure and retries.
    #[test]
    fn an_unrecognisable_dump_yields_no_addresses(){
        assert!(parse_mon_addrs(&json!({})).is_empty());
        assert!(parse_mon_addrs(&json!({"mons": []})).is_empty());
        assert!(parse_mon_addrs(&json!({"mons": [{"name": "n"}]})).is_empty());
    }
}
