apiVersion: v2
name: whoogle-search
description: A self-hosted, ad-free, privacy-respecting metasearch engine
type: application
version: 0.1.1
appVersion: 1.2.4
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Whoogle Search
  yolab.io/icon: 🌐
  yolab.io/category: networking
  yolab.io/tagline: A self-hosted, ad-free, privacy-respecting metasearch engine
  yolab.io/github: benbusby/whoogle-search
home: https://github.com/benbusby
