repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: nix-fmt
        name: nix fmt
        entry: nix run .#format
        language: system
        pass_filenames: false

      - id: nix-lint
        name: deadnix / shellcheck / hadolint
        entry: nix build --no-link .#checks.x86_64-linux.deadnix
          .#checks.x86_64-linux.shellcheck
          .#checks.x86_64-linux.hadolint
        language: system
        pass_filenames: false
