apiVersion: v2
name: llama-gpt
description: Self-hosted, offline ChatGPT-like chatbot powered by Llama 2
type: application
version: 0.1.1
appVersion: 1.0.0
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: LlamaGPT
  yolab.io/icon: 🧠
  yolab.io/category: ai
  yolab.io/tagline: Self-hosted, offline ChatGPT-like chatbot powered by Llama 2
  yolab.io/github: getumbrel/llama-gpt
home: https://umbrel.com
