apiVersion: v2
name: restreamer
description: An easy to use open source video server
type: application
version: 0.1.1
appVersion: 2.12.0
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Restreamer
  yolab.io/icon: 📁
  yolab.io/category: files
  yolab.io/tagline: An easy to use open source video server
  yolab.io/github: datarhei/restreamer
  yolab.io/collections: replace-google
home: https://datarhei.com/
