apiVersion: v2
name: zen
description: A simple app for focused and private note-taking
type: application
version: 0.1.1
appVersion: 1.5.0-patch.1
dependencies:
- name: yolab-common
  version: "0.1.14"
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Zen
  yolab.io/icon: 📁
  yolab.io/category: files
  yolab.io/tagline: A simple app for focused and private note-taking
  yolab.io/github: sheshbabu/zen
  yolab.io/collections: replace-google
home: https://www.sheshbabu.com/zen/
