apiVersion: v2
name: telegrapho
description: Private copy and paste between your devices
type: application
version: 0.1.2
appVersion: 1.0.1
dependencies:
- name: yolab-common
  version: "0.1.14"
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Telegrapho
  yolab.io/icon: 🌐
  yolab.io/category: networking
  yolab.io/tagline: Private copy and paste between your devices
  yolab.io/github: egzola/telegrapho
home: https://github.com/egzola/telegrapho
