apiVersion: v2
name: shopstr
description: Shop freely
type: application
version: 0.1.0
appVersion: 0.7.5
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Shopstr
  yolab.io/icon: ₿
  yolab.io/category: bitcoin
  yolab.io/tagline: Shop freely
  yolab.io/github: shopstr-eng/shopstr
home: https://calva.dev
