{{ include "yolab-common.caddyConfigMap" . }}
---
{{ include "yolab-common.uninstallHook" . }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: yolab-cephfs
  resources:
    requests:
      storage: {{ .Values.config.storage_size | default "5Gi" | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  api_key: {{ required "config.api_key is required" .Values.config.api_key | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      securityContext:
        fsGroup: 1001
      initContainers:
      {{- include "yolab-common.wgRegisterInit" . | nindent 6 }}
      {{- include "yolab-common.fileExplorerInit" . | nindent 6 }}
      containers:
      {{- include "yolab-common.gatewayContainers" . | nindent 6 }}
      - name: shlink
        image: shlinkio/shlink:stable@sha256:77b8eb87bcb1a56bd0ecc590398d415545e5ba83414f28d37dc565a91c3c50b2
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
          - -c
          - |
            . /yolab/env
            export DEFAULT_DOMAIN="$YOLAB_FQDN"
            exec /bin/sh ./docker-entrypoint.sh
        env:
          - name: DB_DRIVER
            value: "sqlite"
          - name: IS_HTTPS_ENABLED
            value: "true"
          - name: INITIAL_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secrets
                key: api_key
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 20
          failureThreshold: 6
        volumeMounts:
          - name: data
            mountPath: /etc/shlink/data
            subPath: {{ .Release.Name }}/shlink
          - name: yolab
            mountPath: /yolab
      volumes:
      {{- include "yolab-common.gatewayVolumes" . | nindent 6 }}
