apiVersion: v2
name: linkstack
description: A highly customizable link sharing platform
type: application
version: 0.1.1
appVersion: 4.8.6
dependencies:
- name: yolab-common
  version: "0.1.14"
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: LinkStack
  yolab.io/icon: 📁
  yolab.io/category: files
  yolab.io/tagline: A highly customizable link sharing platform
  yolab.io/github: LinkStackOrg/LinkStack
  yolab.io/collections: replace-google
home: https://linkstack.org/
