apiVersion: v2
name: blinko
description: An AI-powered hub for your ideas and notes
type: application
version: 0.1.0
appVersion: 1.8.8-patch.1
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Blinko
  yolab.io/icon: 📁
  yolab.io/category: files
  yolab.io/tagline: An AI-powered hub for your ideas and notes
  yolab.io/github: blinko-space/blinko
  yolab.io/collections: replace-google
home: https://blinko-demo.vercel.app/
