{{ include "yolab-common.caddyConfigMap" . }}
---
{{ include "yolab-common.fileExplorerSecret" . }}
---
{{ include "yolab-common.fileExplorerConfigMap" . }}
---
{{ include "yolab-common.privateAccessResources" . }}
---
{{ include "yolab-common.uninstallHook" . }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: yolab-cephfs
  resources:
    requests:
      storage: {{ .Values.config.storage_size | default "10Gi" | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      initContainers:
      {{- include "yolab-common.wgRegisterInit" . | nindent 6 }}
      {{- include "yolab-common.fileExplorerInit" . | nindent 6 }}
      {{- include "yolab-common.privateAccessInit" . | nindent 6 }}
      containers:
      {{- include "yolab-common.gatewayContainers" . | nindent 6 }}
      {{- include "yolab-common.fileExplorerContainer" . | nindent 6 }}
      {{- include "yolab-common.privateAccessContainers" . | nindent 6 }}
      - name: app
        image: etherpad/etherpad:3.3.7@sha256:6f87beef31d91e4a44c7e3fe64043dd294f70443a80267a77267bdac704819a1
        imagePullPolicy: IfNotPresent
        env:
        - name: ('NODE_ENV', 'production')
          value: ''
        - name: ('CI', 'true')
          value: ''
        - name: ('ADMIN_PASSWORD', '${APP_PASSWORD}')
          value: ''
        - name: ('DB_CHARSET', 'utf8mb4')
          value: ''
        - name: ('DB_HOST', 'etherpad_postgres_1')
          value: ''
        - name: ('DB_NAME', 'etherpad')
          value: ''
        - name: ('DB_PASS', 'admin')
          value: ''
        - name: ('DB_PORT', 5432)
          value: ''
        - name: ('DB_TYPE', 'postgres')
          value: ''
        - name: ('DB_USER', 'admin')
          value: ''
        - name: ('DEFAULT_PAD_TEXT', None)
          value: ''
        - name: ('DISABLE_IP_LOGGING', 'false')
          value: ''
        - name: ('LOGLEVEL', 'INFO')
          value: ''
        - name: ('SOFFICE', None)
          value: ''
        - name: ('ALLOW_UNKNOWN_FILE_ENDS', 'true')
          value: ''
        - name: ('TRUST_PROXY', 'true')
          value: ''
        - name: ('SKIN_NAME', 'colibris')
          value: ''
        - name: ('SKIN_VARIANTS', 'super-light-toolbar super-light-editor light-background')
          value: ''
        - name: ('SHOW_SETTINGS_IN_ADMIN_PAGE', 'true')
          value: ''
        - name: ('SUPPRESS_ERRORS_IN_PAD_TEXT', 'false')
          value: ''
        securityContext:
          runAsUser: 5001
          runAsGroup: 0
        ports:
        - containerPort: 9001
        readinessProbe:
          tcpSocket:
            port: 9001
        volumeMounts:
        - name: data
          mountPath: /opt/etherpad-lite/src/plugin_packages
          subPath: '{{ .Release.Name }}/data/plugins'
        - name: data
          mountPath: /opt/etherpad-lite/var
          subPath: '{{ .Release.Name }}/data/etherpad-var'
      volumes:
      {{- include "yolab-common.gatewayVolumes" . | nindent 6 }}
      {{- include "yolab-common.fileExplorerVolumes" . | nindent 6 }}
      {{- include "yolab-common.privateAccessVolumes" . | nindent 6 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine@sha256:93a6166360be8f1d116b7ea97ebb8dea9e2c9c746349e952738bbba72a961d7c
        imagePullPolicy: IfNotPresent
        env:
        - name: ('POSTGRES_DB', 'etherpad')
          value: ''
        - name: ('POSTGRES_PASSWORD', 'admin')
          value: ''
        - name: ('POSTGRES_PORT', 5432)
          value: ''
        - name: ('POSTGRES_USER', 'admin')
          value: ''
        - name: ('PGDATA', '/var/lib/postgresql/data/pgdata')
          value: ''
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        ports:
        - containerPort: 5432
        readinessProbe:
          tcpSocket:
            port: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data/pgdata
          subPath: '{{ .Release.Name }}/data/postgres_data'
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: '{{ .Release.Name }}-data'
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: '{{ .Release.Namespace }}'
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
