config:
  subdomain: mailarchiver
  storage_size: 10Gi
yolab:
  platformApiUrl: ''
  accountToken: ''
  serviceName: ''
  gateway:
    upstream: localhost:5000
  fileExplorer:
    protect:
    - data/database
