config:
  media_folder: ""
  download_client: qbittorrent
  existing_client: ""
  hardware_transcoding: true
  requests: true
  subtitles: false
  watch_anywhere: true
  tailscale: false
  tailscale_auth_key: ""
  manage_anywhere: true
yolab:
  apps: {}
