apiVersion: v2
name: music-assistant
description: A music library manager for your offline and online music sources
type: application
version: 0.1.1
appVersion: 2.10.5
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Music Assistant
  yolab.io/icon: 🎬
  yolab.io/category: media
  yolab.io/tagline: A music library manager for your offline and online music
  yolab.io/github: music-assistant/server
  yolab.io/collections: watch-and-listen
home: https://www.music-assistant.io
