apiVersion: v2
name: unifi
description: "The controller for UniFi access points and switches"
home: https://ui.com
type: application
version: 0.1.0
dependencies:
  - name: yolab-common
    version: "0.1.0"
    repository: "oci://ghcr.io/demycode/charts"
annotations:
  yolab.io/display-name: "UniFi Network"
  yolab.io/icon: "📡"
  yolab.io/category: "networking"
  yolab.io/uischema: |
    { "subdomain": { "ui:widget": "TunnelWidget" } }
