config:
  subdomain: unifi
  storage_size: 10Gi
yolab:
  platformApiUrl: ""
  accountToken: ""
  serviceName: ""
  gateway:
    upstream: localhost:8443
    caddyfile: |
      {$YOLAB_FQDN} {
        reverse_proxy localhost:8443 {
          transport http {
            tls
            tls_insecure_skip_verify
          }
        }
      }
