apiVersion: v2
name: watch-your-lan
description: Lightweight network IP scanner
type: application
version: 0.1.0
appVersion: 2.1.4-patch.1
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: WatchYourLAN
  yolab.io/icon: 🌐
  yolab.io/category: networking
  yolab.io/tagline: Lightweight network IP scanner
  yolab.io/github: aceberg/WatchYourLAN
home: https://github.com/aceberg/WatchYourLAN
