apiVersion: v2
name: minecraft
description: "Minecraft Java Edition server"
home: https://www.minecraft.net
type: application
version: 0.1.3

dependencies:
  - name: yolab-common
    version: "0.1.2"
    repository: "oci://ghcr.io/demycode/charts"

annotations:
  yolab.io/display-name: "Minecraft"
  yolab.io/icon: "⛏️"
  yolab.io/category: "gaming"
