apiVersion: v2
name: jellyseerr
description: "Request manager for Jellyfin media libraries"
home: https://github.com/fallenbagel/jellyseerr
type: application
version: 0.1.9
appVersion: "2"

dependencies:
  - name: yolab-common
    version: "0.1.8"
    repository: "oci://ghcr.io/demycode/charts"

annotations:
  yolab.io/display-name: "Jellyseerr"
  yolab.io/icon: "🎬"
  yolab.io/category: "media"
