apiVersion: v2
name: hermes-agent
description: The AI agent that grows with you
type: application
version: 0.1.2
appVersion: 2026.9.24
dependencies:
- name: yolab-common
  version: "0.1.14"
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Hermes Agent
  yolab.io/icon: 🧠
  yolab.io/category: ai
  yolab.io/tagline: The AI agent that grows with you
  yolab.io/github: NousResearch/hermes-agent
home: https://hermes-agent.nousresearch.com
