apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: yolab-nvidia-cdi-plugin
  namespace: kube-system
  labels:
    app.kubernetes.io/name: yolab-nvidia-cdi-plugin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: yolab-nvidia-cdi-plugin
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: yolab-nvidia-cdi-plugin
    spec:
      priorityClassName: system-node-critical
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: yolab.io/gpu-nvidia
                operator: In
                values: ["true"]
            - matchExpressions:
              - key: yolab.io/gpu-nvidia-legacy
                operator: In
                values: ["true"]
      tolerations:
      - operator: Exists
      containers:
      - name: generic-cdi-plugin
        image: ghcr.io/demycode/generic-cdi-plugin:7d12b0c@sha256:436e6f9091ebe27645f365140a0f28a244d8f5b4a7c518a7760e8d47f6561ede
        imagePullPolicy: IfNotPresent
        command:
        - /generic-cdi-plugin
        - /var/run/cdi/nvidia-container-toolkit.json
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
          limits:
            memory: 64Mi
        securityContext:
          privileged: true
        volumeMounts:
        - name: kubelet
          mountPath: /var/lib/kubelet
        - name: nvidia-cdi-spec
          mountPath: /var/run/cdi/nvidia-container-toolkit.json
          readOnly: true
      volumes:
      - name: kubelet
        hostPath:
          path: /var/lib/kubelet
      - name: nvidia-cdi-spec
        hostPath:
          path: /var/run/cdi/nvidia-container-toolkit.json
          type: File
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: yolab-device-plugin
  namespace: kube-system
  labels:
    app.kubernetes.io/name: yolab-device-plugin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: yolab-device-plugin
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: yolab-device-plugin
    spec:
      priorityClassName: system-node-critical
      tolerations:
      - operator: Exists
      containers:
      - name: generic-device-plugin
        image: docker.io/squat/generic-device-plugin:latest@sha256:dc192e164c69b03f156765793a1be62ca437709ae477b27ca7d8f3dcf5021576
        imagePullPolicy: IfNotPresent
        args:
        - --domain
        - yolab.io
        - --device
        - |
          name: dri
          groups:
            - count: 16
              paths:
                - path: /dev/dri
        - --device
        - |
          name: kfd
          groups:
            - count: 16
              paths:
                - path: /dev/kfd
                - path: /dev/dri
        - --device
        - |
          name: uinput
          groups:
            - count: 4
              paths:
                - path: /dev/uinput
                - path: /dev/uhid
                  optional: true
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            memory: 32Mi
        securityContext:
          privileged: true
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
        - name: dev
          mountPath: /dev
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: dev
        hostPath:
          path: /dev
