apiVersion: v2
name: maybe
description: The OS for your personal finances
type: application
version: 0.1.1
appVersion: 0.6.0
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Maybe
  yolab.io/icon: 💰
  yolab.io/category: finance
  yolab.io/tagline: The OS for your personal finances
  yolab.io/github: maybe-finance/maybe
home: https://maybe.co/
