config:
  subdomain: maybe
  storage_size: 10Gi
yolab:
  platformApiUrl: ''
  accountToken: ''
  serviceName: ''
  gateway:
    upstream: localhost:3063
  fileExplorer:
    protect:
    - data/postgres
    - data/redis
