apiVersion: v2
name: bitmagnet
description: Self-hosted BitTorrent indexer and DHT crawler
type: application
version: 0.1.1
appVersion: v0.10.0-patch.1
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Bitmagnet
  yolab.io/icon: 🎬
  yolab.io/category: media
  yolab.io/tagline: Self-hosted BitTorrent indexer and DHT crawler
  yolab.io/github: bitmagnet-io/bitmagnet
  yolab.io/collections: watch-and-listen
home: https://bitmagnet.io/
