apiVersion: v2
name: super-productivity
description: An efficient way to manage tasks, time, and projects all in one place
type: application
version: 0.1.0
appVersion: 19.1.0
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Super Productivity
  yolab.io/icon: 📁
  yolab.io/category: files
  yolab.io/tagline: An efficient way to manage tasks, time, and projects all in
  yolab.io/github: johannesjo/super-productivity
  yolab.io/collections: replace-google
home: https://super-productivity.com/
