apiVersion: v2
name: cobalt
description: Best way to save what you love
type: application
version: 0.1.2
appVersion: '11.5'
dependencies:
- name: yolab-common
  version: "0.1.14"
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: cobalt
  yolab.io/icon: 🎬
  yolab.io/category: media
  yolab.io/tagline: Best way to save what you love
  yolab.io/github: imputnet/cobalt
  yolab.io/collections: watch-and-listen
home: https://cobalt.tools/
