apiVersion: v2
name: influxdb2
description: The leading platform for time series data
type: application
version: 0.1.0
appVersion: 2.9.1-patch.1
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: InfluxDB 2
  yolab.io/icon: 🛠
  yolab.io/category: developer
  yolab.io/tagline: The leading platform for time series data
  yolab.io/github: influxdata/influxdb
  yolab.io/collections: for-developers
home: https://www.influxdata.com/
