apiVersion: v2
name: homebox
description: An inventory and organization system built for the home user
type: application
version: 0.1.1
appVersion: 0.26.2-patch.1
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: HomeBox
  yolab.io/icon: 📁
  yolab.io/category: files
  yolab.io/tagline: An inventory and organization system built for the home user
  yolab.io/github: sysadminsmedia/homebox
  yolab.io/collections: replace-google
home: https://homebox.software
