apiVersion: v2
name: airtrail
description: A modern, open-source personal flight tracking system
type: application
version: 0.1.2
appVersion: 3.13.0
dependencies:
- name: yolab-common
  version: "0.1.14"
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: AirTrail
  yolab.io/icon: 📁
  yolab.io/category: files
  yolab.io/tagline: A modern, open-source personal flight tracking system
  yolab.io/github: johanohly/AirTrail
  yolab.io/collections: replace-google
home: https://airtrail.johan.ohly.dk
