apiVersion: v2
name: networkingtoolbox
description: The all-in-one offline-first networking toolbox for sysadmins
type: application
version: 0.1.1
appVersion: 1.6.0
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Networking Toolbox
  yolab.io/icon: 🛠
  yolab.io/category: developer
  yolab.io/tagline: The all-in-one offline-first networking toolbox for
  yolab.io/github: Lissy93/networking-toolbox
  yolab.io/collections: for-developers
home: https://www.networkingtoolbox.net/
