{{ include "yolab-common.caddyConfigMap" . }}
---
{{ include "yolab-common.fileExplorerSecret" . }}
---
{{ include "yolab-common.fileExplorerConfigMap" . }}
---
{{ include "yolab-common.privateAccessResources" . }}
---
{{ include "yolab-common.uninstallHook" . }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: yolab-cephfs
  resources:
    requests:
      storage: {{ .Values.config.storage_size | default "10Gi" | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      initContainers:
      {{- include "yolab-common.wgRegisterInit" . | nindent 6 }}
      {{- include "yolab-common.fileExplorerInit" . | nindent 6 }}
      {{- include "yolab-common.privateAccessInit" . | nindent 6 }}
      containers:
      {{- include "yolab-common.gatewayContainers" . | nindent 6 }}
      {{- include "yolab-common.fileExplorerContainer" . | nindent 6 }}
      {{- include "yolab-common.privateAccessContainers" . | nindent 6 }}
      - name: web
        image: ghcr.io/caramelfur/picsur:0.5.6@sha256:209ce21d338cd7d9a1adc838a67695e903149359bf192359819607df1b3c4417
        imagePullPolicy: IfNotPresent
        env:
        - name: ('PICSUR_PORT', 8286)
          value: ''
        - name: ('PICSUR_DB_HOST', 'picsur_db_1')
          value: ''
        - name: ('PICSUR_DB_PORT', 5432)
          value: ''
        - name: ('PICSUR_DB_USERNAME', 'picsuruser')
          value: ''
        - name: ('PICSUR_DB_PASSWORD', 'picsurpass')
          value: ''
        - name: ('PICSUR_DB_DATABASE', 'picsur')
          value: ''
        - name: ('PICSUR_ADMIN_PASSWORD', '${APP_PASSWORD}')
          value: ''
        - name: ('PICSUR_MAX_FILE_SIZE', 128000000000)
          value: ''
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        ports:
        - containerPort: 8286
        readinessProbe:
          tcpSocket:
            port: 8286
      volumes:
      {{- include "yolab-common.gatewayVolumes" . | nindent 6 }}
      {{- include "yolab-common.fileExplorerVolumes" . | nindent 6 }}
      {{- include "yolab-common.privateAccessVolumes" . | nindent 6 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres:17.4@sha256:fe3f571d128e8efadcd8b2fde0e2b73ebab6dbec33f6bfe69d98c682c7d8f7bd
        imagePullPolicy: IfNotPresent
        env:
        - name: ('POSTGRES_DB', 'picsur')
          value: ''
        - name: ('POSTGRES_USER', 'picsuruser')
          value: ''
        - name: ('POSTGRES_PASSWORD', 'picsurpass')
          value: ''
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        ports:
        - containerPort: 5432
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -q
            - -d
            - picsur
            - -U
            - picsuruser
          periodSeconds: 10
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
          subPath: '{{ .Release.Name }}/data/db'
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: '{{ .Release.Name }}-data'
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: '{{ .Release.Namespace }}'
spec:
  selector:
    app: db
  ports:
  - port: 5432
    targetPort: 5432
