{{ include "yolab-common.caddyConfigMap" . }}
---
{{ include "yolab-common.fileExplorerSecret" . }}
---
{{ include "yolab-common.fileExplorerConfigMap" . }}
---
{{ include "yolab-common.privateAccessResources" . }}
---
{{ include "yolab-common.uninstallHook" . }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: yolab-cephfs
  resources:
    requests:
      storage: {{ .Values.config.storage_size | default "10Gi" | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      initContainers:
      {{- include "yolab-common.wgRegisterInit" . | nindent 6 }}
      {{- include "yolab-common.fileExplorerInit" . | nindent 6 }}
      {{- include "yolab-common.privateAccessInit" . | nindent 6 }}
      containers:
      {{- include "yolab-common.gatewayContainers" . | nindent 6 }}
      {{- include "yolab-common.fileExplorerContainer" . | nindent 6 }}
      {{- include "yolab-common.privateAccessContainers" . | nindent 6 }}
      - name: web
        image: ghcr.io/toeverything/affine:0.27.4@sha256:b649f5ce2384ffdf13c23bccf81d759e15973d59d0b0058af65d895a84373099
        imagePullPolicy: IfNotPresent
        env:
        - name: ('AFFINE_CONFIG_PATH', '/root/.affine/config')
          value: ''
        - name: ('REDIS_SERVER_HOST', 'affine_redis_1')
          value: ''
        - name: ('DATABASE_URL', 'postgres://affine:affine@affine_db_1:5432/affine')
          value: ''
        - name: ('AFFINE_INDEXER_ENABLED', 'false')
          value: ''
        - name: ('NODE_ENV', 'production')
          value: ''
        ports:
        - containerPort: 3010
        readinessProbe:
          tcpSocket:
            port: 3010
        volumeMounts:
        - name: data
          mountPath: /root/.affine/config
          subPath: '{{ .Release.Name }}/data/config'
        - name: data
          mountPath: /root/.affine/storage
          subPath: '{{ .Release.Name }}/data/storage/blob'
      volumes:
      {{- include "yolab-common.gatewayVolumes" . | nindent 6 }}
      {{- include "yolab-common.fileExplorerVolumes" . | nindent 6 }}
      {{- include "yolab-common.privateAccessVolumes" . | nindent 6 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: migration
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: migration
  template:
    metadata:
      labels:
        app: migration
    spec:
      containers:
      - name: migration
        image: ghcr.io/toeverything/affine:0.27.4@sha256:b649f5ce2384ffdf13c23bccf81d759e15973d59d0b0058af65d895a84373099
        imagePullPolicy: IfNotPresent
        args:
        - sh
        - -c
        - node ./scripts/self-host-predeploy.js
        env:
        - name: ('AFFINE_CONFIG_PATH', '/root/.affine/config')
          value: ''
        - name: ('REDIS_SERVER_HOST', 'affine_redis_1')
          value: ''
        - name: ('DATABASE_URL', 'postgres://affine:affine@affine_db_1:5432/affine')
          value: ''
        - name: ('AFFINE_INDEXER_ENABLED', 'false')
          value: ''
        - name: ('NODE_ENV', 'production')
          value: ''
        volumeMounts:
        - name: data
          mountPath: /root/.affine/config
          subPath: '{{ .Release.Name }}/data/config'
        - name: data
          mountPath: /root/.affine/storage
          subPath: '{{ .Release.Name }}/data/storage/blob'
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: '{{ .Release.Name }}-data'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: redis
        image: redis:7.2.4@sha256:e647cfe134bf5e8e74e620f66346f93418acfc240b71dd85640325cb7cd01402
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        readinessProbe:
          exec:
            command:
            - redis-cli
            - --raw
            - incr
            - ping
          periodSeconds: 10
        volumeMounts:
        - name: data
          mountPath: /data
          subPath: '{{ .Release.Name }}/data/storage/redis'
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: '{{ .Release.Name }}-data'
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: '{{ .Release.Namespace }}'
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres:16.2@sha256:f58300ac8d393b2e3b09d36ea12d7d24ee9440440e421472a300e929ddb63460
        imagePullPolicy: IfNotPresent
        env:
        - name: ('POSTGRES_USER', 'affine')
          value: ''
        - name: ('POSTGRES_PASSWORD', 'affine')
          value: ''
        - name: ('POSTGRES_DB', 'affine')
          value: ''
        - name: ('PGDATA', '/var/lib/postgresql/data/pgdata')
          value: ''
        ports:
        - containerPort: 5432
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U affine
          periodSeconds: 10
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
          subPath: '{{ .Release.Name }}/data/storage/postgres'
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: '{{ .Release.Name }}-data'
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: '{{ .Release.Namespace }}'
spec:
  selector:
    app: db
  ports:
  - port: 5432
    targetPort: 5432
