apiVersion: v2
name: lobe-chat
description: Your self-hosted AI workspace for chat, agents, and knowledge
type: application
version: 0.1.4
appVersion: 2.2.17
dependencies:
- name: yolab-common
  version: "0.1.15"
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Lobe Hub
  yolab.io/icon: 🧠
  yolab.io/category: ai
  yolab.io/tagline: Your self-hosted AI workspace for chat, agents, and
  yolab.io/github: lobehub/lobehub
home: https://lobehub.com/
