apiVersion: v2
name: code-server
description: "VS Code in the browser, running on your own hardware"
home: https://coder.com/docs/code-server
type: application
version: 0.1.9
appVersion: "4"

dependencies:
  - name: yolab-common
    version: "0.1.8"
    repository: "oci://ghcr.io/demycode/charts"

annotations:
  yolab.io/display-name: "code-server"
  yolab.io/icon: "💻"
  yolab.io/category: "development"
