apiVersion: v2
name: localai
description: Drop-in OpenAI replacement
type: application
version: 0.1.2
appVersion: v4.11.0
dependencies:
- name: yolab-common
  version: "0.1.14"
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: LocalAI
  yolab.io/icon: 🧠
  yolab.io/category: ai
  yolab.io/tagline: Drop-in OpenAI replacement
  yolab.io/github: mudler/LocalAI
home: https://localai.io/
