apiVersion: v2
name: radarr
description: "Follows films you want and fetches them when they become available"
home: https://radarr.video
type: application
version: 0.1.17

dependencies:
  - name: yolab-common
    version: "0.1.15"
    repository: "oci://ghcr.io/demycode/charts"

annotations:
  yolab.io/display-name: "Radarr"
  yolab.io/icon: "🎬"
  yolab.io/category: "media"
  yolab.io/github: "Radarr/Radarr"
  yolab.io/tagline: "Automatically find and organise movies"
  yolab.io/collections: "watch-and-listen"
