apiVersion: v2
name: mqttx-web
description: Your All-in-One MQTT Client Toolbox
type: application
version: 0.1.2
appVersion: 1.13.1
dependencies:
- name: yolab-common
  version: "0.1.15"
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: MQTTX Web
  yolab.io/icon: 🤖
  yolab.io/category: automation
  yolab.io/tagline: Your All-in-One MQTT Client Toolbox
  yolab.io/github: emqx/MQTTX
home: https://mqttx.app/
