apiVersion: v2
name: sikka
description: Feeless, quantum-safe cryptocurrency node
type: application
version: 0.1.0
appVersion: 0.2.0-patch.1
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Sikka
  yolab.io/icon: 🧩
  yolab.io/category: crypto
  yolab.io/tagline: Feeless, quantum-safe cryptocurrency node
  yolab.io/github: sikkalabs/sikka
home: https://github.com/sikkalabs
