
config:
  subdomain: healthchecks
  admin_email: admin@example.com
  admin_password: ""
  storage_size: 2Gi

yolab:
  platformApiUrl: ""
  accountToken: ""
  serviceName: ""
  gateway:
    upstream: localhost:8000
