apiVersion: v2
name: kiwix
description: Access knowledge anytime, anywhere without an internet connection
type: application
version: 0.1.2
appVersion: 3.8.2-patch.1
dependencies:
- name: yolab-common
  version: "0.1.15"
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Kiwix
  yolab.io/icon: 📁
  yolab.io/category: files
  yolab.io/tagline: Access knowledge anytime, anywhere without an internet
  yolab.io/github: kiwix/kiwix-tools
  yolab.io/collections: replace-google
home: https://kiwix.org
