apiVersion: v2
name: perplexica
description: An AI-powered answering engine
type: application
version: 0.1.2
appVersion: 1.12.2-patch.1
dependencies:
- name: yolab-common
  version: "0.1.15"
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Vane
  yolab.io/icon: 🧠
  yolab.io/category: ai
  yolab.io/tagline: An AI-powered answering engine
  yolab.io/github: ItzCrazyKns/Vane
home: https://github.com/ItzCrazyKns/Vane
