apiVersion: v2
name: immich
description: "Self-hosted photo and video backup"
home: https://immich.app
type: application
version: 0.2.8

dependencies:
  - name: yolab-common
    version: "0.1.12"
    repository: "oci://ghcr.io/demycode/charts"

annotations:
  yolab.io/display-name: "Immich"
  yolab.io/icon: "📸"
  yolab.io/category: "media"
