config:
  subdomain: immich
  hardware_acceleration: true
gpu: {}
yolab:
  fileExplorer:
    protect:
    - postgres
  platformApiUrl: ''
  accountToken: ''
  serviceName: ''
  gateway:
    upstream: immich-server:2283
