apiVersion: v2
name: langflow
description: Build AI agents and workflows visually
type: application
version: 0.1.1
appVersion: 1.12.4
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Langflow
  yolab.io/icon: 🧠
  yolab.io/category: ai
  yolab.io/tagline: Build AI agents and workflows visually
  yolab.io/github: langflow-ai/langflow
home: https://www.langflow.org/
