apiVersion: v2
name: pinchflat
description: A automated media backup solution, for online media sources
type: application
version: 0.1.0
appVersion: 2025.6.6-patch.1
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Pinchflat
  yolab.io/icon: 🎬
  yolab.io/category: media
  yolab.io/tagline: A automated media backup solution, for online media sources
  yolab.io/github: kieraneglin/pinchflat
  yolab.io/collections: watch-and-listen
home: https://github.com/kieraneglin/pinchflat
