apiVersion: v2
name: mailflow
description: Unified self-hosted webmail client
type: application
version: 0.1.1
appVersion: 3.8.2
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: MailFlow
  yolab.io/icon: 🌐
  yolab.io/category: networking
  yolab.io/tagline: Unified self-hosted webmail client
  yolab.io/github: maathimself/mailflow
home: https://mailflow.sh
