config:
  subdomain: mailflow
  storage_size: 10Gi
yolab:
  platformApiUrl: ''
  accountToken: ''
  serviceName: ''
  gateway:
    upstream: frontend:80
  fileExplorer:
    protect:
    - data/postgres
    - data/redis
