apiVersion: v2
name: onlyoffice-nextcloud
description: Online office for Nextcloud
type: application
version: 0.1.2
appVersion: 9.4.0-1-patch.1
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/disabled: "Duplicate of onlyoffice"
  yolab.io/display-name: ONLYOFFICE Docs
  yolab.io/icon: 📁
  yolab.io/category: files
  yolab.io/tagline: Online office for Nextcloud
  yolab.io/github: ONLYOFFICE/DocumentServer
  yolab.io/collections: replace-google
home: https://www.onlyoffice.com/
