apiVersion: v2
name: reactive-resume
description: "Free and open source resume builder"
home: https://rxresu.me
type: application
version: 0.1.12

dependencies:
  - name: yolab-common
    version: "0.1.9"
    repository: "oci://ghcr.io/demycode/charts"

annotations:
  yolab.io/display-name: "Reactive Resume"
  yolab.io/icon: "📄"
  yolab.io/category: "productivity"
