apiVersion: v2
name: etherpad
description: An intuitive tool for real-time collaborative writing
type: application
version: 0.1.2
appVersion: 3.3.7
dependencies:
- name: yolab-common
  version: "0.1.14"
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Etherpad
  yolab.io/icon: 📁
  yolab.io/category: files
  yolab.io/tagline: An intuitive tool for real-time collaborative writing
  yolab.io/github: ether/etherpad
  yolab.io/collections: replace-google
home: https://etherpad.org/
