{{ include "yolab-common.caddyConfigMap" . }}
---
{{ include "yolab-common.fileExplorerSecret" . }}
---
{{ include "yolab-common.fileExplorerConfigMap" . }}
---
{{ include "yolab-common.privateAccessResources" . }}
---
{{ include "yolab-common.uninstallHook" . }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: yolab-cephfs
  resources:
    requests:
      storage: {{ .Values.config.storage_size | default "10Gi" | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  admin_password: {{ required "config.admin_password is required" .Values.config.admin_password | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- if .Values.config.node }}
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.config.node | quote }}
      {{- else }}
      {{- end }}
      initContainers:
      {{- include "yolab-common.wgRegisterInit" . | nindent 6 }}
      {{- include "yolab-common.fileExplorerInit" . | nindent 6 }}
      {{- include "yolab-common.privateAccessInit" . | nindent 6 }}
      containers:
      {{- include "yolab-common.gatewayContainers" . | nindent 6 }}
      {{- include "yolab-common.fileExplorerContainer" . | nindent 6 }}
      {{- include "yolab-common.privateAccessContainers" . | nindent 6 }}
      - name: server
        image: pihole/pihole:2026.09.0@sha256:5b9c8cf51de7d6d3f2240dbe72baf5f06e1fd39cb4d77a99fab4fa13e23bd1be
        imagePullPolicy: IfNotPresent
        env:
        - name: APP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: '{{ .Release.Name }}-secrets'
              key: admin_password
        - name: FTLCONF_webserver_api_password
          value: $(APP_PASSWORD)
        - name: FTLCONF_webserver_port
          value: 8082,[::]:8082
        - name: FTLCONF_dns_listeningMode
          value: all
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        ports:
        - containerPort: 8082
        readinessProbe:
          tcpSocket:
            port: 8082
        volumeMounts:
        - name: data
          mountPath: /etc/pihole/
          subPath: '{{ .Release.Name }}/data/pihole'
        - name: data
          mountPath: /etc/dnsmasq.d/
          subPath: '{{ .Release.Name }}/data/dnsmasq'
      volumes:
      {{- include "yolab-common.gatewayVolumes" . | nindent 6 }}
      {{- include "yolab-common.fileExplorerVolumes" . | nindent 6 }}
      {{- include "yolab-common.privateAccessVolumes" . | nindent 6 }}
