apiVersion: v2
name: obsidian
description: The private and flexible writing app that adapts to the way you think
type: application
version: 0.1.1
appVersion: 1.8.10-patch.1
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Obsidian
  yolab.io/icon: 📁
  yolab.io/category: files
  yolab.io/tagline: The private and flexible writing app that adapts to the way
  yolab.io/github: linuxserver/docker-obsidian
  yolab.io/collections: replace-google
home: https://obsidian.md/
