
config:
  subdomain: miniflux
  admin_username: admin
  admin_password: ""
  storage_size: 1Gi

yolab:
  platformApiUrl: ""
  accountToken: ""
  serviceName: ""
  gateway:
    upstream: localhost:8080
