apiVersion: v2
name: readur
description: An intuitive OCR platform for documents
type: application
version: 0.1.2
appVersion: 3.0.0
dependencies:
- name: yolab-common
  version: "0.1.14"
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Readur
  yolab.io/icon: 📁
  yolab.io/category: files
  yolab.io/tagline: An intuitive OCR platform for documents
  yolab.io/github: readur/readur
  yolab.io/collections: replace-google
home: https://github.com/readur/readur
