config:
  subdomain: affine
  storage_size: 10Gi
yolab:
  platformApiUrl: ''
  accountToken: ''
  serviceName: ''
  gateway:
    upstream: localhost:3010
  fileExplorer:
    protect:
    - data/storage/postgres
    - data/storage/redis
