apiVersion: v2
name: convertx
description: Self-hosted online file converter
type: application
version: 0.1.0
appVersion: 0.19.0
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: ConvertX
  yolab.io/icon: 📁
  yolab.io/category: files
  yolab.io/tagline: Self-hosted online file converter
  yolab.io/github: C4illin/ConvertX
  yolab.io/collections: replace-google
home: https://github.com/C4illin/ConvertX
