apiVersion: v2
name: dropgate-server
description: Self-hosted, privacy-first file sharing with hosted upload and P2P transfer
type: application
version: 0.1.1
appVersion: 3.0.13-patch.1
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Dropgate Server
  yolab.io/icon: 📁
  yolab.io/category: files
  yolab.io/tagline: Self-hosted, privacy-first file sharing with hosted upload
  yolab.io/github: diamonddigitaldev/Dropgate
  yolab.io/collections: replace-google
home: https://diamonddigital.dev/projects/dropgate
