apiVersion: v2
name: docmost
description: "Collaborative wiki and documentation workspace"
home: https://docmost.com
type: application
version: 0.1.11
appVersion: "0.10"

dependencies:
  - name: yolab-common
    version: "0.1.10"
    repository: "oci://ghcr.io/demycode/charts"

annotations:
  yolab.io/display-name: "Docmost"
  yolab.io/icon: "📚"
  yolab.io/category: "productivity"
