apiVersion: v2
name: nextcloud
description: "Files, calendar, contacts and photos, self-hosted"
home: https://nextcloud.com
type: application
version: 0.1.13
appVersion: "31"

dependencies:
  - name: yolab-common
    version: "0.1.12"
    repository: "oci://ghcr.io/demycode/charts"

annotations:
  yolab.io/display-name: "Nextcloud"
  yolab.io/icon: "☁️"
  yolab.io/category: "productivity"
