
config:
  subdomain: nextcloud
  admin_user: "admin"
  admin_password: ""
  storage_size: 50Gi

yolab:
  platformApiUrl: ""
  accountToken: ""
  serviceName: ""
  gateway:
    upstream: nextcloud:80
