apiVersion: v2
name: pastefy
description: An easy paste for seamless sharing
type: application
version: 0.1.4
appVersion: 7.1.6-patch.1
dependencies:
- name: yolab-common
  version: "0.1.15"
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Pastefy
  yolab.io/icon: 🛠
  yolab.io/category: developer
  yolab.io/tagline: An easy paste for seamless sharing
  yolab.io/github: interaapps/pastefy
  yolab.io/collections: for-developers
home: https://pastefy.app/
