apiVersion: v2
name: bffless
description: Self-hosted static site hosting platform
type: application
version: 0.1.2
appVersion: 0.4.15
dependencies:
- name: yolab-common
  version: "0.1.14"
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: BFFless
  yolab.io/icon: 🛠
  yolab.io/category: developer
  yolab.io/tagline: Self-hosted static site hosting platform
  yolab.io/github: bffless/ce
  yolab.io/collections: for-developers
home: https://docs.bffless.app/deployment/umbrel/
