apiVersion: v2
name: karakeep
description: "Bookmark and read-later app with automatic tagging"
home: https://karakeep.app
type: application
version: 0.1.8
appVersion: "0.23"

dependencies:
  - name: yolab-common
    version: "0.1.7"
    repository: "oci://ghcr.io/demycode/charts"

annotations:
  yolab.io/display-name: "Karakeep"
  yolab.io/icon: "🐿️"
  yolab.io/category: "productivity"
