config:
  subdomain: ghostfolio
  storage_size: 10Gi
yolab:
  platformApiUrl: ''
  accountToken: ''
  serviceName: ''
  gateway:
    upstream: localhost:3334
  fileExplorer:
    protect:
    - data/postgres
    - data/redis
