apiVersion: v2
name: influxdb
description: High performance time series database
type: application
version: 0.1.1
appVersion: 1.13.1
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: InfluxDB
  yolab.io/icon: 🛠
  yolab.io/category: developer
  yolab.io/tagline: High performance time series database
  yolab.io/github: influxdata/influxdb
  yolab.io/collections: for-developers
home: https://www.influxdata.com/
