apiVersion: v2
name: seafile
description: Reliable and Performant File Sync and Share Solution
type: application
version: 0.1.1
appVersion: 13.0.28
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Seafile
  yolab.io/icon: 📁
  yolab.io/category: files
  yolab.io/tagline: Reliable and Performant File Sync and Share Solution
  yolab.io/github: haiwen/seafile
  yolab.io/collections: replace-google
home: https://www.seafile.com/
