"""Initial migration with SQLModel

Revision ID: 22dde5817298
Revises:
Create Date: 2026-01-21 17:03:22.458313

"""
# type: ignore

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "22dde5817298"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "services",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("service_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "service_type",
            sa.Enum("http", "https", "tcp", "udp", name="servicetype"),
            nullable=False,
        ),
        sa.Column("subdomain", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("remote_port", sa.Integer(), nullable=True),
        sa.Column("local_port", sa.Integer(), nullable=False),
        sa.Column("auth_token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("api_token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "suspended", "deleted", name="servicestatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("api_token"),
        sa.UniqueConstraint("auth_token"),
    )
    op.create_index(
        op.f("ix_services_remote_port"), "services", ["remote_port"], unique=True
    )
    op.create_index(
        op.f("ix_services_subdomain"), "services", ["subdomain"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_services_subdomain"), table_name="services")
    op.drop_index(op.f("ix_services_remote_port"), table_name="services")
    op.drop_table("services")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
