"""empty message

Revision ID: 7be337326cae
Revises: c3d4e5f6a7b8
Create Date: 2026-03-04 17:44:48.815065

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7be337326cae"
down_revision: Union[str, Sequence[str], None] = "c3d4e5f6a7b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_services_wg_public_key"), table_name="services")
    op.create_unique_constraint(None, "services", ["wg_public_key"])
    op.drop_column("services", "service_type")
    op.drop_column("services", "client_port")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "services",
        sa.Column("client_port", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "services",
        sa.Column(
            "service_type",
            postgresql.ENUM("tcp", "udp", name="servicetype"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "services", type_="unique")
    op.create_index(
        op.f("ix_services_wg_public_key"), "services", ["wg_public_key"], unique=True
    )
    # ### end Alembic commands ###
