"""ok

Revision ID: a26048365ab2
Revises: 25adf160268f
Create Date: 2026-02-05 13:48:05.022502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a26048365ab2'
down_revision: Union[str, Sequence[str], None] = '25adf160268f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_subdomain'), table_name='services')
    op.drop_column('services', 'local_port')
    op.drop_column('services', 'subdomain')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('subdomain', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('services', sa.Column('local_port', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_services_subdomain'), 'services', ['subdomain'], unique=True)
    # ### end Alembic commands ###
