"""empty message

Revision ID: b99b8db45565
Revises: 7be337326cae
Create Date: 2026-03-05 23:11:40.460029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b99b8db45565'
down_revision: Union[str, Sequence[str], None] = '7be337326cae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('services_wg_public_key_key'), 'services', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('services_wg_public_key_key'), 'services', ['wg_public_key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
