"""New counter mechanism

Revision ID: c10f9da35509
Revises: 2600bb567c83
Create Date: 2026-02-04 16:25:31.744923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c10f9da35509'
down_revision: Union[str, Sequence[str], None] = '2600bb567c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ipv6_counter')
    op.add_column('services', sa.Column('sub_ipv6', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('services', sa.Column('client_port', sa.Integer(), nullable=False))
    op.add_column('services', sa.Column('frps_internal_port', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_services_ipv6_address'), table_name='services')
    op.create_index(op.f('ix_services_sub_ipv6'), 'services', ['sub_ipv6'], unique=True)
    op.create_unique_constraint(None, 'services', ['frps_internal_port'])
    op.drop_column('services', 'local_port')
    op.drop_column('services', 'last_seen')
    op.drop_column('services', 'created_at')
    op.drop_column('services', 'ipv6_address')
    op.drop_column('services', 'remote_port')
    op.drop_column('services', 'status')
    op.drop_column('services', 'service_name')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('services', sa.Column('service_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('services', sa.Column('status', postgresql.ENUM('active', 'suspended', 'deleted', name='servicestatus'), autoincrement=False, nullable=False))
    op.add_column('services', sa.Column('remote_port', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('services', sa.Column('ipv6_address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('services', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('services', sa.Column('last_seen', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('services', sa.Column('local_port', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'services', type_='unique')
    op.drop_index(op.f('ix_services_sub_ipv6'), table_name='services')
    op.create_index(op.f('ix_services_ipv6_address'), 'services', ['ipv6_address'], unique=True)
    op.drop_column('services', 'frps_internal_port')
    op.drop_column('services', 'client_port')
    op.drop_column('services', 'sub_ipv6')
    op.create_table('ipv6_counter',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('counter', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ipv6_counter_pkey'))
    )
    # ### end Alembic commands ###
