"""empty message

Revision ID: d9e29b504b79
Revises: 106c343e96c7
Create Date: 2026-03-06 11:45:11.307018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd9e29b504b79'
down_revision: Union[str, Sequence[str], None] = '106c343e96c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_services_wg_public_key'), 'services', ['wg_public_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_wg_public_key'), table_name='services')
    # ### end Alembic commands ###
