"""Add web service type

Revision ID: dc745c552096
Revises: 22dde5817298
Create Date: 2026-01-21 18:38:02.244534

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "dc745c552096"
down_revision: Union[str, Sequence[str], None] = "22dde5817298"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
