apiVersion: v2
name: ollama
description: Self-host open source AI models like DeepSeek-R1, Llama, and more
type: application
version: 0.2.1
appVersion: 0.35.1
dependencies:
- name: yolab-common
  version: "0.1.14"
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Ollama
  yolab.io/icon: 🧠
  yolab.io/category: ai
  yolab.io/tagline: Self-host open source AI models like DeepSeek-R1, Llama
  yolab.io/github: ollama/ollama
home: https://ollama.com/
