apiVersion: v2
name: sure
description: The personal finance app for everyone
type: application
version: 0.1.1
appVersion: 0.7.5
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Sure
  yolab.io/icon: 💰
  yolab.io/category: finance
  yolab.io/tagline: The personal finance app for everyone
  yolab.io/github: we-promise/sure
home: https://sure.am
