apiVersion: v2
name: mainsail
description: Control and monitor your printer from everywhere, from any device
type: application
version: 0.1.1
appVersion: 2.19.0
dependencies:
- name: yolab-common
  version: "0.1.14"
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Mainsail
  yolab.io/icon: 📁
  yolab.io/category: files
  yolab.io/tagline: Control and monitor your printer from everywhere, from any
  yolab.io/github: mainsail-crew/mainsail
  yolab.io/collections: replace-google
home: https://docs.mainsail.xyz/
