apiVersion: v2
name: palmr
description: Open-Source File Transfer
type: application
version: 0.1.0
appVersion: 3.3.2-beta
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Palmr
  yolab.io/icon: 📁
  yolab.io/category: files
  yolab.io/tagline: Open-Source File Transfer
  yolab.io/github: kyantech/Palmr
  yolab.io/collections: replace-google
home: https://palmr.kyantech.com.br/
