apiVersion: v2
name: photoprism
description: "AI-powered photo library with face and object recognition"
home: https://www.photoprism.app
type: application
version: 0.1.11
appVersion: "240915"

dependencies:
  - name: yolab-common
    version: "0.1.9"
    repository: "oci://ghcr.io/demycode/charts"

annotations:
  yolab.io/display-name: "PhotoPrism"
  yolab.io/icon: "📷"
  yolab.io/category: "media"
