apiVersion: v2
name: ghost
description: "Publishing platform for blogs and newsletters"
home: https://ghost.org
type: application
version: 0.1.9
appVersion: "5"

dependencies:
  - name: yolab-common
    version: "0.1.8"
    repository: "oci://ghcr.io/demycode/charts"

annotations:
  yolab.io/display-name: "Ghost"
  yolab.io/icon: "👻"
  yolab.io/category: "media"
