apiVersion: v2
name: nginx-proxy-manager
description: Expose your services easily and securely
type: application
version: 0.1.0
appVersion: 2.16.0
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Nginx Proxy Manager
  yolab.io/icon: 🌐
  yolab.io/category: networking
  yolab.io/tagline: Expose your services easily and securely
  yolab.io/github: NginxProxyManager/nginx-proxy-manager
home: https://nginxproxymanager.com/
