apiVersion: v2
name: vikunja
description: "Tasks, projects and kanban boards"
home: https://vikunja.io
type: application
version: 0.1.11
appVersion: "0.24"

dependencies:
  - name: yolab-common
    version: "0.1.10"
    repository: "oci://ghcr.io/demycode/charts"

annotations:
  yolab.io/display-name: "Vikunja"
  yolab.io/icon: "✅"
  yolab.io/category: "productivity"
