apiVersion: v2
name: freshrss
description: "Self-hosted RSS and Atom feed aggregator"
home: https://freshrss.org
type: application
version: 0.1.7
appVersion: "1"

dependencies:
  - name: yolab-common
    version: "0.1.6"
    repository: "oci://ghcr.io/demycode/charts"

annotations:
  yolab.io/display-name: "FreshRSS"
  yolab.io/icon: "📰"
  yolab.io/category: "media"
