apiVersion: v2
name: tandoor
description: Organize recipes, meal plans, and shopping lists
type: application
version: 0.1.2
appVersion: 2.6.15-patch.1
dependencies:
- name: yolab-common
  version: "0.1.14"
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Tandoor Recipes
  yolab.io/icon: 📁
  yolab.io/category: files
  yolab.io/tagline: Organize recipes, meal plans, and shopping lists
  yolab.io/github: TandoorRecipes/recipes
  yolab.io/collections: replace-google
home: https://tandoor.dev/
