apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v19.2.0
  dataDirHostPath: /var/lib/rook
  mon:
    count: 1
    allowMultiplePerNode: true
  mgr:
    count: 1
    allowMultiplePerNode: true
  dashboard:
    enabled: false
  crashCollector:
    disable: true
  logCollector:
    enabled: false
  cephConfig:
    global:
      osd_pool_default_min_size: "1"
      osd_memory_target: "268435456"
      bluestore_cache_autotune: "true"
  priorityClassNames:
    mon: system-cluster-critical
    mgr: system-cluster-critical
    osd: system-cluster-critical
  storage:
    useAllNodes: true
    useAllDevices: true
  resources:
    mgr:
      limits:
        memory: "512Mi"
      requests:
        memory: "128Mi"
        cpu: "50m"
    mgr-sidecar:
      limits:
        memory: "64Mi"
      requests:
        memory: "32Mi"
        cpu: "10m"
    mon:
      limits:
        memory: "256Mi"
      requests:
        memory: "64Mi"
        cpu: "50m"
    osd:
      limits:
        memory: "512Mi"
      requests:
        memory: "256Mi"
        cpu: "100m"
    prepareosd:
      limits:
        memory: "256Mi"
      requests:
        memory: "64Mi"
        cpu: "50m"
---
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: yolab-fs
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 1
      requireSafeReplicaSize: false
  dataPools:
    - name: data0
      replicated:
        size: 1
        requireSafeReplicaSize: false
  preserveFilesystemOnDelete: true
  metadataServer:
    activeCount: 1
    activeStandby: false
    priorityClassName: system-cluster-critical
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        memory: "512Mi"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: yolab-cephfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: rook-ceph.cephfs.csi.ceph.com
parameters:
  clusterID: rook-ceph
  fsName: yolab-fs
  pool: yolab-fs-data0
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
