apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rook-ceph
  namespace: kube-system
spec:
  repo: https://charts.rook.io/release
  chart: rook-ceph
  version: v1.16.3
  targetNamespace: rook-ceph
  createNamespace: true
  valuesContent: |-
    allowLoopDevices: true
    resources:
      limits:
        memory: 256Mi
      requests:
        memory: 128Mi
        cpu: 100m
    cephCommandsTimeoutSeconds: "60"
    csi:
      enableCephfsDriver: true
      enableRbdDriver: false
      provisionerReplicas: 1
      grpcTimeoutInSeconds: 300
