apiVersion: v2
name: pi-hole
description: Block ads on your entire network
type: application
version: 0.1.1
appVersion: 2026.09.0
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Pi-hole
  yolab.io/icon: 🌐
  yolab.io/category: networking
  yolab.io/tagline: Block ads on your entire network
  yolab.io/github: pi-hole/docker-pi-hole
home: https://pi-hole.net
