services:
  wg-sidecar:
    build: ../wg-sidecar
    container_name: wg-sidecar
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    volumes:
      - ./wg0.conf:/etc/wireguard/wg0.conf:ro
    restart: unless-stopped

  librespeed:
    image: lscr.io/linuxserver/librespeed:latest
    container_name: librespeed
    network_mode: "service:wg-sidecar"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=PASSWORD
      - CUSTOM_RESULTS=false
      - DB_TYPE=sqlite
    volumes:
      - librespeed_config:/config
    depends_on:
      - wg-sidecar
    restart: unless-stopped

volumes:
  librespeed_config:
