apiVersion: v2
name: pocketbase
description: Open Source backend for your next SaaS and Mobile app in 1 file
type: application
version: 0.1.0
appVersion: 0.40.4-patch.1
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: PocketBase
  yolab.io/icon: 🛠
  yolab.io/category: developer
  yolab.io/tagline: Open Source backend for your next SaaS and Mobile app in 1
  yolab.io/github: pocketbase/pocketbase
  yolab.io/collections: for-developers
home: https://pocketbase.io/
