{{ include "yolab-common.caddyConfigMap" . }}
---
{{ include "yolab-common.fileExplorerSecret" . }}
---
{{ include "yolab-common.fileExplorerConfigMap" . }}
---
{{ include "yolab-common.privateAccessResources" . }}
---
{{ include "yolab-common.uninstallHook" . }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: yolab-cephfs
  resources:
    requests:
      storage: {{ .Values.config.storage_size | default "10Gi" | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  app_secret: {{ required "config.app_secret is required" .Values.config.app_secret | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      initContainers:
      {{- include "yolab-common.wgRegisterInit" . | nindent 6 }}
      {{- include "yolab-common.fileExplorerInit" . | nindent 6 }}
      {{- include "yolab-common.privateAccessInit" . | nindent 6 }}
      containers:
      {{- include "yolab-common.gatewayContainers" . | nindent 6 }}
      {{- include "yolab-common.fileExplorerContainer" . | nindent 6 }}
      {{- include "yolab-common.privateAccessContainers" . | nindent 6 }}
      - name: web
        image: ceramicwhite/invidious:build-fda8d1b@sha256:39fe17102eb65ff34ac83e4d2b7f4233e735c1221e3c881fd0e0919b78760f81
        imagePullPolicy: IfNotPresent
        env:
        - name: APP_SEED
          valueFrom:
            secretKeyRef:
              name: '{{ .Release.Name }}-secrets'
              key: app_secret
        - name: INVIDIOUS_CONFIG
          value: "db:\n  dbname: invidious\n  user: umbrel\n  password: moneyprintergobrrr\n  host: postgres\n  port: 5432\ncheck_tables: true\ninvidious_companion:\n- private_url: \"http://companion:8282/companion\"\ninvidious_companion_key: $(APP_SEED)\nhmac_key: $(APP_SEED)\ndefault_user_preferences:\n  feed_menu: [\"Trending\", \"Subscriptions\", \"Playlists\"]\n  default_home: Trending\n"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        ports:
        - containerPort: 3000
        readinessProbe:
          tcpSocket:
            port: 3000
      volumes:
      {{- include "yolab-common.gatewayVolumes" . | nindent 6 }}
      {{- include "yolab-common.fileExplorerVolumes" . | nindent 6 }}
      {{- include "yolab-common.privateAccessVolumes" . | nindent 6 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13.23@sha256:4689940c683801b4ab839ab3b0a0a3555a5fe425371422310944e89eca7d8068
        imagePullPolicy: IfNotPresent
        env:
        - name: APP_SEED
          valueFrom:
            secretKeyRef:
              name: '{{ .Release.Name }}-secrets'
              key: app_secret
        - name: POSTGRES_DB
          value: invidious
        - name: POSTGRES_USER
          value: umbrel
        - name: POSTGRES_PASSWORD
          value: moneyprintergobrrr
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        ports:
        - containerPort: 5432
        readinessProbe:
          tcpSocket:
            port: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
          subPath: '{{ .Release.Name }}/data/db'
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: '{{ .Release.Name }}-data'
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: '{{ .Release.Namespace }}'
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: companion
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: companion
  template:
    metadata:
      labels:
        app: companion
    spec:
      containers:
      - name: companion
        image: quay.io/invidious/invidious-companion:master-6c76cab@sha256:aaec4e18b3cffb5457633f427c834299677f2c2a7e27b598404ab815643c3747
        imagePullPolicy: IfNotPresent
        env:
        - name: APP_SEED
          valueFrom:
            secretKeyRef:
              name: '{{ .Release.Name }}-secrets'
              key: app_secret
        - name: SERVER_SECRET_KEY
          value: $(APP_SEED)
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        volumeMounts:
        - name: data
          mountPath: /var/tmp/youtubei.js
          subPath: '{{ .Release.Name }}/data/companioncache'
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: '{{ .Release.Name }}-data'
