apiVersion: v2
name: filebrowser
description: Web-based file manager for your storage (FileBrowser Quantum)
home: https://github.com/gtsteffaniak/filebrowser
type: application
version: 0.1.13
appVersion: "2.1.0-beta"

dependencies:
  - name: yolab-common
    version: "0.1.9"
    repository: "oci://ghcr.io/demycode/charts"

annotations:
  yolab.io/display-name: "File Browser"
  yolab.io/icon: "🗂️"
  yolab.io/category: "utilities"
