
config:
  subdomain: filebrowser
  password: ""
  storage_size: 50Gi
  file_explorer_enabled: false

yolab:
  platformApiUrl: ""
  accountToken: ""
  serviceName: ""
  gateway:
    upstream: filebrowser:80
