apiVersion: v2
name: forgejo
description: A self-hosted lightweight software forge
type: application
version: 0.1.0
appVersion: 16.0.5
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Forgejo
  yolab.io/icon: 🛠
  yolab.io/category: developer
  yolab.io/tagline: A self-hosted lightweight software forge
  yolab.io/collections: for-developers
home: https://forgejo.org/
