apiVersion: v2
name: appsmith
description: Platform to build admin panels, internal tools, and dashboards
type: application
version: 0.1.1
appVersion: v2.4.3
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Appsmith
  yolab.io/icon: 🛠
  yolab.io/category: developer
  yolab.io/tagline: Platform to build admin panels, internal tools, and
  yolab.io/github: appsmithorg/appsmith
  yolab.io/collections: for-developers
home: https://www.appsmith.com/
