{{- $c := .Values.config }}
{{- $folder := dict "media_folder" $c.media_folder }}
{{- $manage := dict "yolab_enabled" $c.manage_anywhere }}
{{- $watch := dict "yolab_enabled" $c.watch_anywhere "tailscale_enabled" $c.tailscale }}
{{- if $c.tailscale }}
{{- $_ := set $watch "tailscale_auth_key" $c.tailscale_auth_key }}
{{- end }}
apiVersion: yolab.io/v1
kind: App
name: jellyfin
chart: jellyfin
main: true
values: {{ merge (dict "hardware_transcoding" $c.hardware_transcoding) $folder $watch | toJson }}
---
apiVersion: yolab.io/v1
kind: App
name: sonarr
chart: sonarr
values: {{ merge (dict) $folder $manage | toJson }}
---
apiVersion: yolab.io/v1
kind: App
name: radarr
chart: radarr
values: {{ merge (dict) $folder $manage | toJson }}
---
apiVersion: yolab.io/v1
kind: App
name: prowlarr
chart: prowlarr
values: {{ $manage | toJson }}
{{- if eq $c.download_client "existing" }}
---
apiVersion: yolab.io/v1
kind: App
name: download-client
use: {{ $c.existing_client | quote }}
{{- else if ne $c.download_client "none" }}
---
apiVersion: yolab.io/v1
kind: App
name: {{ $c.download_client }}
chart: {{ $c.download_client }}
values: {{ merge (dict) $folder $manage | toJson }}
{{- end }}
{{- if $c.requests }}
---
apiVersion: yolab.io/v1
kind: App
name: jellyseerr
chart: jellyseerr
values: {{ $watch | toJson }}
{{- end }}
{{- if $c.subtitles }}
---
apiVersion: yolab.io/v1
kind: App
name: bazarr
chart: bazarr
values: {{ merge (dict) $folder $manage | toJson }}
{{- end }}
