apiVersion: v2
name: solidtime
description: A simple, secure, and private time tracking app
type: application
version: 0.1.0
appVersion: 0.21.0
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Solidtime
  yolab.io/icon: 📁
  yolab.io/category: files
  yolab.io/tagline: A simple, secure, and private time tracking app
  yolab.io/github: solidtime-io/solidtime
  yolab.io/collections: replace-google
home: https://www.solidtime.io/
