#!/usr/bin/env python3
"""Download a real logo for every catalog app and regenerate the manifest.

    nix develop --command python3 scripts/fetch-icons.py

Run this after adding a chart. Icons are committed and served from the box
rather than hotlinked: a house with no working internet is exactly when someone
opens this dashboard, and one CDN request per app would also tell a third party
which apps each household runs — the same reasoning that pulled the webfonts
in-tree.

Only the full-colour variant is taken. selfh.st also ships `<name>-light`, but
that is a flat white silhouette rather than a version tuned for dark
backgrounds — using it in dark mode would strip the gradient out of Jellyfin
and the colour out of everything else. Legibility on dark is handled in the UI
instead, by rendering every logo on a light plate the way a phone home screen
does.
"""

import os
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CATALOG = os.path.join(ROOT, "apps/catalog")
OUT_DIR = os.path.join(ROOT, "homelab/client-ui/public/icons")
MANIFEST = os.path.join(ROOT, "homelab/client-ui/src/catalog/icons.ts")

SELFHST = "https://cdn.jsdelivr.net/gh/selfhst/icons"
DASHBOARD = "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons"

# Charts whose upstream logo is filed under a different name.
ALIASES = {
    "actual": "actual-budget",
    # code-server is VS Code in a browser tab, and has no mark of its own.
    "code-server": "vscode",
}

# Above this an SVG is almost always a traced raster, and a downscaled PNG is
# both smaller and identical on screen. memos shipped a 245 KB one.
SVG_MAX_BYTES = 40_000
PNG_MAX_PX = 128


def fetch(url: str) -> bytes | None:
    r = subprocess.run(["curl", "-sfL", "--max-time", "20", url], capture_output=True)
    return r.stdout if r.returncode == 0 and r.stdout else None


def shrink_png(path: str) -> None:
    if not shutil.which("magick"):
        return
    subprocess.run(
        ["magick", path, "-resize", f"{PNG_MAX_PX}x{PNG_MAX_PX}", "-strip", path],
        check=False,
    )


def main() -> int:
    ids = sorted(
        d
        for d in os.listdir(CATALOG)
        if os.path.isdir(os.path.join(CATALOG, d)) and d != "yolab-common"
    )
    os.makedirs(OUT_DIR, exist_ok=True)
    for old in os.listdir(OUT_DIR):
        os.remove(os.path.join(OUT_DIR, old))

    found: dict[str, str] = {}
    missing: list[str] = []

    for app_id in ids:
        name = ALIASES.get(app_id, app_id)
        svg = fetch(f"{SELFHST}/svg/{name}.svg") or fetch(f"{DASHBOARD}/svg/{name}.svg")
        png = None
        if svg is None or len(svg) > SVG_MAX_BYTES:
            png = fetch(f"{SELFHST}/png/{name}.png") or fetch(
                f"{DASHBOARD}/png/{name}.png"
            )

        if png is not None:
            path = os.path.join(OUT_DIR, f"{app_id}.png")
            with open(path, "wb") as f:
                f.write(png)
            shrink_png(path)
            found[app_id] = f"/icons/{app_id}.png"
        elif svg is not None:
            path = os.path.join(OUT_DIR, f"{app_id}.svg")
            with open(path, "wb") as f:
                f.write(svg)
            found[app_id] = f"/icons/{app_id}.svg"
        else:
            missing.append(app_id)

    lines = [
        "// GENERATED by scripts/fetch-icons.py — do not edit by hand.",
        "//",
        "// Real project logos, committed and served from this box rather than",
        "// hotlinked from a CDN: a house with no working internet is exactly when",
        "// someone opens this dashboard, and one request per app would also tell a",
        "// third party which apps each household runs.",
        "//",
        "// Third-party logos, used to identify the projects they belong to. Sourced",
        "// from selfh.st/icons and homarr-labs/dashboard-icons. Apps with no entry",
        "// here — and anything from a user-added repo — fall back to the emoji in",
        "// their Chart.yaml.",
        "",
        "export const CATALOG_ICONS: Record<string, string> = {",
    ]
    lines += [f'  "{k}": "{found[k]}",' for k in sorted(found)]
    lines += ["};", ""]
    with open(MANIFEST, "w") as f:
        f.write("\n".join(lines))

    print(f"icons: {len(found)} of {len(ids)}")
    if missing:
        print("no logo found (emoji fallback):", " ".join(missing))
    return 0


if __name__ == "__main__":
    sys.exit(main())
