config:
  subdomain: activepieces
  storage_size: 10Gi
yolab:
  platformApiUrl: ''
  accountToken: ''
  serviceName: ''
  gateway:
    upstream: app:80
  fileExplorer:
    protect:
    - data/db
    - data/redis
