apiVersion: v2
name: appflowy
description: "Open-source alternative to Notion. Docs, wikis, and projects in one place."
home: https://appflowy.io
type: application
version: 0.2.6

dependencies:
  - name: yolab-common
    version: "0.1.5"
    repository: "oci://ghcr.io/demycode/charts"

annotations:
  yolab.io/display-name: "AppFlowy"
  yolab.io/icon: "https://raw.githubusercontent.com/AppFlowy-IO/AppFlowy/main/frontend/resources/flowy_icons/ic_appflowy.png"
  yolab.io/category: "productivity"
