apiVersion: v2
name: librespeed
description: "Self-hosted internet speed test"
home: https://librespeed.org
type: application
version: 0.1.8

dependencies:
  - name: yolab-common
    version: "0.1.7"
    repository: "oci://ghcr.io/demycode/charts"

annotations:
  yolab.io/display-name: "LibreSpeed"
  yolab.io/icon: "⚡"
  yolab.io/category: "utilities"
