apiVersion: v2
name: portainer
description: Run custom Docker containers on your Umbrel
type: application
version: 0.1.1
appVersion: 2.45.1-1
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Portainer
  yolab.io/icon: 🛠
  yolab.io/category: developer
  yolab.io/tagline: Run custom Docker containers on your Umbrel
  yolab.io/github: portainer/portainer
  yolab.io/collections: for-developers
home: https://portainer.io
