apiVersion: v2
name: ntfy
description: "Self-hosted push notification service"
home: https://ntfy.sh
type: application
version: 0.1.15

dependencies:
  - name: yolab-common
    version: "0.1.13"
    repository: "oci://ghcr.io/demycode/charts"

annotations:
  yolab.io/display-name: "ntfy"
  yolab.io/icon: "🔔"
  yolab.io/category: "utilities"
  yolab.io/github: "binwiederhier/ntfy"
  yolab.io/tagline: "Push notifications to your phone from anything"
  yolab.io/collections: "privacy"
