apiVersion: v2
name: libretranslate
description: Free and Open Source machine translation API
type: application
version: 0.1.2
appVersion: 1.6.5
dependencies:
- name: yolab-common
  version: "0.1.14"
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: LibreTranslate
  yolab.io/icon: 🧠
  yolab.io/category: ai
  yolab.io/tagline: Free and Open Source machine translation API
  yolab.io/github: LibreTranslate/LibreTranslate
home: https://libretranslate.com
