{{ include "yolab-common.caddyConfigMap" . }}
---
{{ include "yolab-common.fileExplorerSecret" . }}
---
{{ include "yolab-common.fileExplorerConfigMap" . }}
---
{{ include "yolab-common.privateAccessResources" . }}
---
{{ include "yolab-common.uninstallHook" . }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: yolab-cephfs
  resources:
    requests:
      storage: {{ .Values.config.storage_size | default "10Gi" | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      initContainers:
      {{- include "yolab-common.wgRegisterInit" . | nindent 6 }}
      {{- include "yolab-common.fileExplorerInit" . | nindent 6 }}
      {{- include "yolab-common.privateAccessInit" . | nindent 6 }}
      containers:
      {{- include "yolab-common.gatewayContainers" . | nindent 6 }}
      {{- include "yolab-common.fileExplorerContainer" . | nindent 6 }}
      {{- include "yolab-common.privateAccessContainers" . | nindent 6 }}
      - name: web
        image: willtda/dropgate-server:3.0.13@sha256:43698790fe341ea3fb0094bbdca701ecdf875a9c4b9c92b67f86c34c887c132b
        imagePullPolicy: IfNotPresent
        env:
        - name: ('SERVER_PORT', 52443)
          value: ''
        - name: ('SERVER_NAME', 'Dropgate Server')
          value: ''
        - name: ('ENABLE_WEB_UI', 'true')
          value: ''
        - name: ('ENABLE_UPLOAD', 'true')
          value: ''
        - name: ('UPLOAD_ENABLE_E2EE', 'true')
          value: ''
        - name: ('UPLOAD_PRESERVE_UPLOADS', 'false')
          value: ''
        - name: ('UPLOAD_MAX_FILE_SIZE_MB', 100)
          value: ''
        - name: ('UPLOAD_MAX_STORAGE_GB', 10)
          value: ''
        - name: ('UPLOAD_MAX_FILE_LIFETIME_HOURS', 24)
          value: ''
        - name: ('UPLOAD_MAX_FILE_DOWNLOADS', 1)
          value: ''
        - name: ('ENABLE_P2P', 'true')
          value: ''
        ports:
        - containerPort: 52443
        readinessProbe:
          tcpSocket:
            port: 52443
        volumeMounts:
        - name: data
          mountPath: /usr/src/app/uploads
          subPath: '{{ .Release.Name }}/data/uploads'
      volumes:
      {{- include "yolab-common.gatewayVolumes" . | nindent 6 }}
      {{- include "yolab-common.fileExplorerVolumes" . | nindent 6 }}
      {{- include "yolab-common.privateAccessVolumes" . | nindent 6 }}
