apiVersion: v2
name: cinny
description: "Modern Matrix web client"
home: https://cinny.in
type: application
version: 0.1.15

dependencies:
  - name: yolab-common
    version: "0.1.13"
    repository: "oci://ghcr.io/demycode/charts"

annotations:
  yolab.io/display-name: "Cinny"
  yolab.io/icon: "💬"
  yolab.io/category: "communication"
  yolab.io/github: "cinnyapp/cinny"
  yolab.io/tagline: "A clean, modern Matrix chat client"
