apiVersion: v2
name: trilium-notes
description: Build your personal knowledge base with Trilium Notes
type: application
version: 0.1.1
appVersion: v0.106.0
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Trilium Notes
  yolab.io/icon: 📁
  yolab.io/category: files
  yolab.io/tagline: Build your personal knowledge base with Trilium Notes
  yolab.io/github: TriliumNext/Trilium
  yolab.io/collections: replace-google
home: https://github.com/TriliumNext
