apiVersion: v2
name: jackett
description: API support for your favorite torrent trackers
type: application
version: 0.1.1
appVersion: 0.24.2793
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Jackett
  yolab.io/icon: 🎬
  yolab.io/category: media
  yolab.io/tagline: API support for your favorite torrent trackers
  yolab.io/github: Jackett/Jackett
  yolab.io/collections: watch-and-listen
home: https://github.com/Jackett/Jackett/
