apiVersion: v2
name: uptime-kuma
description: "Self-hosted uptime monitor with status pages and alerting"
home: https://uptime.kuma.pet
type: application
version: 0.1.6
appVersion: "1"

dependencies:
  - name: yolab-common
    version: "0.1.5"
    repository: "oci://ghcr.io/demycode/charts"

annotations:
  yolab.io/display-name: "Uptime Kuma"
  yolab.io/icon: "📈"
  yolab.io/category: "monitoring"
