apiVersion: v2
name: pingvin-share
description: Self-hosted file sharing platform
type: application
version: 0.1.2
appVersion: 1.13.0
dependencies:
- name: yolab-common
  version: "0.1.14"
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/disabled: "Upstream repository is archived"
  yolab.io/display-name: Pingvin Share
  yolab.io/icon: 📁
  yolab.io/category: files
  yolab.io/tagline: Self-hosted file sharing platform
  yolab.io/github: stonith404/pingvin-share
  yolab.io/collections: replace-google
home: https://stonith404.github.io/pingvin-share/introduction
