
config:
  subdomain: mastodon
  owner_username: admin
  owner_email: admin@example.com
  smtp_server: ""
  smtp_port: 587
  smtp_login: ""
  smtp_password: ""
  smtp_from_address: ""
  storage_size: 30Gi

yolab:
  platformApiUrl: ""
  accountToken: ""
  serviceName: ""
  gateway:
    upstream: mastodon:80
