config:
  subdomain: librechat
  storage_size: 10Gi
yolab:
  platformApiUrl: ''
  accountToken: ''
  serviceName: ''
  gateway:
    upstream: localhost:3080
  fileExplorer:
    protect:
    - data/db
    - data/vectordb
