apiVersion: v2
name: jotty
description: A simple app, for your checklists and notes
type: application
version: 0.1.2
appVersion: 1.28.0
dependencies:
- name: yolab-common
  version: "0.1.14"
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Jotty
  yolab.io/icon: 📁
  yolab.io/category: files
  yolab.io/tagline: A simple app, for your checklists and notes
  yolab.io/github: fccview/jotty
  yolab.io/collections: replace-google
home: https://jotty.page
