apiVersion: v2
name: reitti
description: A location tracking and analysis application
type: application
version: 0.1.2
appVersion: 5.6.1
dependencies:
- name: yolab-common
  version: "0.1.14"
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Reitti
  yolab.io/icon: 📁
  yolab.io/category: files
  yolab.io/tagline: A location tracking and analysis application
  yolab.io/github: dedicatedcode/reitti
  yolab.io/collections: replace-google
home: https://www.dedicatedcode.com/projects/reitti/overview/
