config:
  subdomain: reitti
  storage_size: 10Gi
yolab:
  platformApiUrl: ''
  accountToken: ''
  serviceName: ''
  gateway:
    upstream: localhost:8080
  fileExplorer:
    protect:
    - data/postgis
    - data/redis
