apiVersion: v2
name: kitchenowl
description: A grocery list and recipe manager
type: application
version: 0.1.1
appVersion: 0.7.10-patch.1
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: KitchenOwl
  yolab.io/icon: 📁
  yolab.io/category: files
  yolab.io/tagline: A grocery list and recipe manager
  yolab.io/github: TomBursch/kitchenowl
  yolab.io/collections: replace-google
home: https://kitchenowl.org/
