apiVersion: v2
name: readarr
description: Your book collection manager
type: application
version: 0.1.0
appVersion: 0.4.18.2805
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Readarr
  yolab.io/icon: 🎬
  yolab.io/category: media
  yolab.io/tagline: Your book collection manager
  yolab.io/github: Readarr/Readarr
  yolab.io/collections: watch-and-listen
home: https://readarr.com/
