apiVersion: v2
name: sqlitebrowser
description: A database browser for SQLite
type: application
version: 0.1.0
appVersion: 3.13.1-patch.1
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: SQLite Browser
  yolab.io/icon: 🛠
  yolab.io/category: developer
  yolab.io/tagline: A database browser for SQLite
  yolab.io/github: sqlitebrowser/sqlitebrowser
  yolab.io/collections: for-developers
home: https://sqlitebrowser.org/
