apiVersion: v2
name: monetr
description: A budgeting application focused on planning for recurring expenses
type: application
version: 0.1.1
appVersion: 1.17.1
dependencies:
- name: yolab-common
  version: 0.1.13
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Monetr
  yolab.io/icon: 💰
  yolab.io/category: finance
  yolab.io/tagline: A budgeting application focused on planning for recurring
  yolab.io/github: monetr/monetr
home: https://monetr.app/
