config:
  subdomain: monetr
  storage_size: 10Gi
yolab:
  platformApiUrl: ''
  accountToken: ''
  serviceName: ''
  gateway:
    upstream: localhost:4000
  fileExplorer:
    protect:
    - data/db
    - data/valkey
