#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

TARGET_HOST="${TARGET_HOST:-}"
SSH_KEY="${SSH_KEY:-$HOME/.ssh/id_ed25519}"
SSH_PUBLIC_KEY="${SSH_PUBLIC_KEY:-}"
REPO_URL="${REPO_URL:-https://github.com/yourusername/yolab.git}"
DOMAIN="${DOMAIN:-example.com}"
POSTGRES_DB="${POSTGRES_DB:-frp_services}"
POSTGRES_USER="${POSTGRES_USER:-frp_user}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-}"
IPV6_SUBNET_BASE="${IPV6_SUBNET_BASE:-}"
FRPS_SERVER_IPV6="${FRPS_SERVER_IPV6:-}"

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

usage() {
    cat <<EOF
Usage: $0

Required Environment Variables:
  TARGET_HOST         IP address or hostname of target server
  POSTGRES_PASSWORD   PostgreSQL password
  IPV6_SUBNET_BASE    Base IPv6 subnet
  FRPS_SERVER_IPV6    FRP server IPv6 address

Optional Environment Variables:
  SSH_KEY            SSH private key path (default: ~/.ssh/id_ed25519)
  SSH_PUBLIC_KEY     SSH public key content (auto-detected from SSH_KEY.pub)
  REPO_URL           Git repository URL
  DOMAIN             Domain name (default: example.com)
  POSTGRES_DB        Database name (default: frp_services)
  POSTGRES_USER      Database user (default: frp_user)

Example:
  TARGET_HOST=192.168.1.100 \\
  POSTGRES_PASSWORD=secret123 \\
  IPV6_SUBNET_BASE=2001:db8::1:0:0:0 \\
  FRPS_SERVER_IPV6=2001:db8::1 \\
  DOMAIN=yourdomain.com \\
  ./deploy-all-in-one.sh

EOF
    exit 1
}

check_requirements() {
    log_info "Checking requirements..."
    
    for cmd in nix ssh; do
        if ! command -v "$cmd" &> /dev/null; then
            log_error "Required command not found: $cmd"
            exit 1
        fi
    done
    
    if [[ -z "$TARGET_HOST" ]]; then
        log_error "TARGET_HOST is required"
        usage
    fi
    
    if [[ -z "$POSTGRES_PASSWORD" ]]; then
        log_error "POSTGRES_PASSWORD is required"
        usage
    fi
    
    if [[ -z "$IPV6_SUBNET_BASE" ]]; then
        log_error "IPV6_SUBNET_BASE is required"
        usage
    fi
    
    if [[ -z "$FRPS_SERVER_IPV6" ]]; then
        log_error "FRPS_SERVER_IPV6 is required"
        usage
    fi
    
    if [[ ! -f "$SSH_KEY" ]]; then
        log_error "SSH key not found: $SSH_KEY"
        exit 1
    fi
    
    # Auto-detect SSH public key if not provided
    if [[ -z "$SSH_PUBLIC_KEY" ]]; then
        local pub_key_file="${SSH_KEY}.pub"
        if [[ -f "$pub_key_file" ]]; then
            SSH_PUBLIC_KEY=$(cat "$pub_key_file")
            log_info "Auto-detected SSH public key from $pub_key_file"
        else
            log_error "SSH_PUBLIC_KEY not provided and ${pub_key_file} not found"
            exit 1
        fi
    fi
    
    log_info "All requirements satisfied"
}

create_deployment_config() {
    log_info "Creating deployment configuration..."
    
    local config_dir="$PROJECT_ROOT/deployment/nixos/ignored"
    local config_file="$config_dir/config.toml"
    
    # Create ignored directory if it doesn't exist
    mkdir -p "$config_dir"
    
    # Generate config.toml
    cat > "$config_file" <<EOF
# YoLab Server Deployment Configuration
# Auto-generated by deployment script
# Edit this file to customize your deployment

[server]
hostname = "yolab-server"
domain = "$DOMAIN"
repo_url = "$REPO_URL"

[ssh]
public_key = "$SSH_PUBLIC_KEY"
key_name = "yolab-deployment-key"

[database]
db_name = "$POSTGRES_DB"
db_user = "$POSTGRES_USER"
db_password = "$POSTGRES_PASSWORD"

[network]
ipv6_subnet_base = "$IPV6_SUBNET_BASE"
frps_server_ipv6 = "$FRPS_SERVER_IPV6"
frps_bind_port = 7000
auth_plugin_addr = "127.0.0.1:5000"

[frps]
enable = true

[services]
enable = true
api_host = "0.0.0.0"
api_port = 5000
auto_update = true
open_firewall = true
EOF
    
    log_info "Configuration written to: $config_file"
    echo "$config_file"
}

cleanup_deployment_config() {
    local config_file="$1"
    if [[ -f "$config_file" ]]; then
        log_info "Cleaning up deployment configuration..."
        rm -f "$config_file"
    fi
}

deploy() {
    log_info "Starting deployment to $TARGET_HOST..."
    
    local config_file
    config_file=$(create_deployment_config)
    
    trap "cleanup_deployment_config '$config_file'" EXIT
    
    log_info "Building NixOS configuration..."
    cd "$PROJECT_ROOT"
    nix build ".#nixosConfigurations.yolab-server.config.system.build.toplevel" \
        --extra-experimental-features 'nix-command flakes'
    
    log_info "Building disk partitioner..."
    nix build ".#nixosConfigurations.yolab-server.config.system.build.diskoScript" \
        --extra-experimental-features 'nix-command flakes'
    
    log_info "Deploying to $TARGET_HOST with nixos-anywhere..."
    nix run github:nix-community/nixos-anywhere -- \
        --flake ".#yolab-server" \
        --build-on-remote \
        --ssh-option "IdentityFile=$SSH_KEY" \
        "root@$TARGET_HOST"
    
    log_info "Deployment complete!"
    log_info "You can now SSH to the server using: ssh -i $SSH_KEY root@$TARGET_HOST"
}

main() {
    if [[ "${1:-}" == "-h" ]] || [[ "${1:-}" == "--help" ]]; then
        usage
    fi
    
    check_requirements
    deploy
}

main "$@"
