
config:
  subdomain: homepage
  storage_size: 1Gi

yolab:
  platformApiUrl: ""
  accountToken: ""
  serviceName: ""
  gateway:
    upstream: localhost:3000
    caddyfile: |-
      {$YOLAB_FQDN} {
        reverse_proxy localhost:3000 {
          header_up Host homepage.yolab.internal
        }
      }
