{{- $c := .Values.config }}
{{- $shared := dict "media_folder" $c.music_folder }}
apiVersion: yolab.io/v1
kind: App
name: navidrome
chart: navidrome
main: true
values: {{ merge (dict "music_folder" $c.music_folder) ($c.navidrome | default dict) | toJson }}
---
apiVersion: yolab.io/v1
kind: App
name: lidarr
chart: lidarr
values: {{ merge (dict) $shared ($c.lidarr | default dict) | toJson }}
{{- if eq $c.download_client "existing" }}
---
apiVersion: yolab.io/v1
kind: App
name: download-client
use: {{ $c.existing_client | quote }}
{{- else if ne $c.download_client "none" }}
---
apiVersion: yolab.io/v1
kind: App
name: {{ $c.download_client }}
chart: {{ $c.download_client }}
values: {{ merge (dict) $shared (index $c $c.download_client | default dict) | toJson }}
{{- end }}
