apiVersion: v2
name: nostrudel
description: A sandbox for exploring nostr
type: application
version: 0.1.2
appVersion: 1.1.0
dependencies:
- name: yolab-common
  version: "0.1.14"
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: noStrudel
  yolab.io/icon: 💬
  yolab.io/category: social
  yolab.io/tagline: A sandbox for exploring nostr
  yolab.io/github: hzrd149/nostrudel
home: https://github.com/hzrd149/nostrudel
