apiVersion: v2
name: cashu-me
description: An open-source Bitcoin ecash wallet
type: application
version: 0.1.2
appVersion: 0.1.1
dependencies:
- name: yolab-common
  version: "0.1.15"
  repository: oci://ghcr.io/demycode/charts
annotations:
  yolab.io/display-name: Cashu.me Wallet
  yolab.io/icon: ₿
  yolab.io/category: bitcoin
  yolab.io/tagline: An open-source Bitcoin ecash wallet
  yolab.io/github: cashubtc/cashu.me
home: https://cashu.space
